spring.application.name=ingreso

# Postgres connection (set values for your environment)
spring.datasource.url=jdbc:postgresql://localhost:5432/ingreso
spring.datasource.username=ingreso
spring.datasource.password=ingreso
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema management (empty DB -> tables will be created)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Disable H2 console when using Postgres
spring.h2.console.enabled=false

