spring.application.name=ingreso

# Postgres connection (override via env vars)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ticker_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Schema management (empty DB -> tables will be created)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# H2 console is only applicable when using H2 datasource
spring.h2.console.enabled=false

