package com.empresa.ingreso.shared.errors;

public enum ErrorCode {
    LECTOR_NO_CONFIGURADO,
    TICKET_NO_ENCONTRADO,
    ESTADO_INVALIDO,
    SESION_INVALIDA,
    ZONA_INCORRECTA,
    TICKET_DUPLICADO,
    EVENTO_NO_ENCONTRADO,
    ASIGNACION_CONFLICTIVA,
    REINGRESO_NO_PERMITIDO,
    LIMITE_REINGRESO_EXCEDIDO,
    SALIDA_NO_PERMITIDA,
    ERROR_TECNICO
}
